language: php

php:
    - 7.3
    - 7.4
    - 8.0snapshot

install:
    - travis_retry composer install --no-progress --prefer-dist

script:
    - vendor/bin/tester -s tests

after_failure:
    # Print *.actual content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

dist: bionic

cache:
    directories:
        - $HOME/.composer/cache
